apiVersion: v1
kind: Service
metadata:
  name: spring-test-performance-db
spec:
  type: ClusterIP
  selector:
    app: spring-test-performance-db
  ports:
    - port: 8080
      targetPort: http
      name: http
