apiVersion: v1
kind: Service
metadata:
  name: spring-test-performance-db
spec:
  type: LoadBalancer
  selector:
    app: spring-test-performance-db-general
  ports:
    - port: 6001
      targetPort: http-jmx
      name: http-jmx
